using System.Configuration;
using System.Data;
using System.Windows;

namespace LocalPasswordGenerator;

/// <summary>
/// This class is automatically generated by WPF and is currently unused.
/// It remains in the project to maintain standard WPF application structure.
/// </summary>
public partial class App : Application
{
}

